# Generated by Django 4.2.7 on 2023-11-20 07:20

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='title', help_text='Enter the country title.', max_length=150, unique=True, verbose_name='Title')),
                ('flag', models.URLField(db_column='flag', help_text='Enter the URL for the country flag.', max_length=250, verbose_name='Flag')),
                ('iso3', models.CharField(db_column='iso3', help_text='Enter the three-letter ISO code.', max_length=10, unique=True, verbose_name='ISO Code 3')),
                ('iso2', models.CharField(db_column='iso2', help_text='Enter the two-letter ISO code.', max_length=10, unique=True, verbose_name='ISO Code 2')),
                ('phone_code', models.CharField(db_column='phone_code', help_text='Enter the country phone code.', max_length=5, unique=True, verbose_name='Phone Code')),
                ('currency', models.CharField(db_column='currency', help_text='Enter the country currency.', max_length=20, verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
                'ordering': ['title'],
            },
        ),
    ]
