# Generated by Django 4.2.7 on 2023-12-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(db_column='phone_code', help_text='Enter the country phone code.', max_length=5, verbose_name='Phone Code'),
        ),
    ]
