# Generated by Django 4.2.7 on 2024-02-13 07:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(db_index=True, default='', unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
            ],
        ),
    ]
