# Generated by Django 4.2.7 on 2024-04-15 06:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('algo_app', '0002_algouser_phoneotp_strategy_wallet_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(db_index=True, default='', max_length=12, unique=True)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('username', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTradeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_type', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=10, null=True)),
                ('cepe', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY')], default=None, max_length=10, null=True)),
                ('trade_price', models.CharField(default='0', max_length=10, null=True)),
                ('index', models.CharField(default=None, max_length=25, null=True)),
                ('token', models.IntegerField(default=0)),
                ('symbol', models.CharField(default=None, max_length=40, null=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trades', to='algo_app.user', verbose_name='User-Trades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_strategy', to='algo_app.user', verbose_name='User-Strategy'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='algo_app.user', verbose_name='User-Wallet'),
        ),
        migrations.DeleteModel(
            name='AlgoUser',
        ),
    ]
