# Generated by Django 4.2.7 on 2024-02-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
