# Generated by Django 4.2.7 on 2024-02-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_app', '0004_remove_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
